### PR TITLE
Updated lensingmap.py to add ellmin_data in lensingmap.cluster_maps()

### PR DESCRIPTION
**Pull request by s-Sayan**
Updated to have the xmax option for analitic_kappa_ft().

### CODE REVIEW

**Comment by sayansaha1996** [comment]
The eq 28 and 29 in (https://arxiv.org/pdf/1010.0744.pdf) is FT for a profile truncated at R200 = c*rs, right? I thought it would make it more generalized.

**Comment by s-Sayan** [comment]
Now this pull request only adds ellmin_data in lensingmap.cluster_maps()

**Comment by s-Sayan** [comment]
I have added a new class sim_cmb_len_lss_plus_cluster with a choice using a key = "lss"/"cluster"/"lss_plus_cluster"

**Comment by s-Sayan** [comment]
These commits have been made to the clusterlens branch

**Pull request closed without merging**
